### ISSUE TITLE
Switch to Github actions?

### ISSUE THREAD

**Issue by tomac4t** [citizenlab/test-lists#604] opened 2020-04-04 08:38 UTC
Looks something wrong with Travis CI. Recently, I notice that it doesn't build for Pull Request (in this repo). Maybe should switch to Github actions? Like: 
```yaml
name: check
on: 
  push:
    paths:
    - "lists/*"
  pull_request:
    paths:
    - "lists/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: python scripts/lint-lists.py lists/
```

**Comment by jakubd** [comment] 2020-04-07 18:17
Agreed, tested this on a toy copy of the repo and works well.  I am not sure what the issue is with Travis all the builds are done on the Travis side but the results don't always get posted.

Added your script as the basis in a PR for now. see #606 for more discussion

**Comment by tomac4t** [comment] 2020-04-08 07:27
Move `.github/main.yml` to `.github/workflows/main.yml`? I believe the `.yaml` file only work on `.github/workflows` directory. @jakubd 

Reference: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file

**Comment by jakubd** [comment] 2020-04-08 13:50
You got it!  Fixed some of the names to be a bit more descriptive as well. Thanks!

**Comment by jakubd** [comment] 2020-04-14 13:16
This is merged in now, so no more Travis.  Thanks for the help!

**Closed by jakubd** 2020-04-14 13:16 UTC
